FROM python:3.11
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
WORKDIR /app
COPY ./src .
RUN useradd -d /app -r -U sam && chown sam:sam -R /app
USER sam
ENTRYPOINT ["bash", "entrypoint.sh"]
# ENTRYPOINT ["gunicorn", "main:app", "--workers", "4", \
#    "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:80"]